pipeline:
  ping:
    image: postgres
    commands:
      # wait for postgres service to become available
      - |
        until psql -U postgres -d test -h database \
         -c "SELECT 1;" >/dev/null 2>&1; do sleep 1; done
      # query the database
      - |
        psql -U postgres -d test -h database \
          -c "SELECT * FROM pg_catalog.pg_tables;"

  build docker image:
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t slotlist-info/drone-test/test-build:latest .

  test docker image:
    image: slotlist-info/drone-test/test-build:latest
    commands:
      - pwd
      - ls -ahl
      - yarn test

  build:
    image: node
    commands:
      - yarn
      - yarn build
      - yarn lint
      - yarn test

  gcr:
    image: plugins/gcr
    repo: slotlist-info/drone-test/test-build
    tags: latest
    registry: eu.gcr.io
    secrets: [google_credentials]

services:
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
